version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "4444:4444"
    volumes:
      - /app/node_modules
      - .:/app   
    env_file:
      - .env
  prisma:
    image: prismagraphql/prisma:1.23
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://mongo:27018
            database: pushlog
  mongo:
    image: mongo:4.0.5
    command: mongod --port 27018
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo:
